// An artboard for a gear's panel: artboards/<Name>Mock.dc.html, a standalone page with the panel drawn by
// the app's own component (so the artboard can never drift from the app) and its starting settings.
// Usage: npm run artboard -- <gearId> <Name>
// Builds src/artboard/main.tsx (vite.artboard.config.ts), then inlines the script, the styles and the
// gear's definition (build-only rules left out) into one HTML file.
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import type { GearDef } from '../../shared/schema';
import { OUTPUT_DIR, ROOT } from '../lib/paths';

const [gearId, name] = process.argv.slice(2);
if (!gearId || !name) {
  console.error('usage: npm run artboard -- <gearId> <Name>');
  process.exit(2);
}
const gear: GearDef[] = JSON.parse(fs.readFileSync(path.join(OUTPUT_DIR, 'gear.json'), 'utf8'));
const def = gear.find((d) => d.id === gearId);
if (!def) throw new Error('No gear with id ' + gearId + ' in public/data/gear.json (run npm run build:data)');
const { match: _match, parse: _parse, valueAliases: _aliases, ...panelData } = def; // build-only rules are not panel data

const out = path.join(ROOT, 'dist-artboard');
execFileSync(
  process.execPath,
  [
    path.join(ROOT, 'node_modules/vite/bin/vite.js'),
    'build',
    '--config',
    'vite.artboard.config.ts',
    '--logLevel',
    'warn',
  ],
  { cwd: ROOT, stdio: 'inherit' },
);
const js = fs.readFileSync(path.join(out, 'artboard.js'), 'utf8');
const css = fs.readFileSync(path.join(out, 'artboard.css'), 'utf8');
const safe = (s: string) => s.replace(/<\/(script|style)/gi, '<\\/$1');

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${def.model} panel mock</title>
<!-- Generated by tools/artboard from the app's panel component (src/ui/panels); do not edit by hand. -->
<style>
${safe(css)}
body{padding:24px 16px}
.board{display:flex;flex-direction:column;align-items:center;gap:10px} #panel{max-width:100%;display:flex;flex-direction:column}
.cap{font-size:12px;color:var(--muted)}
</style>
</head>
<body>
<div class="board"><div id="panel"></div><p class="cap">${def.brand} ${def.model} — panel mock. Visual reference only — nothing here controls a physical amp.</p></div>
<script type="application/json" id="panel-data">${JSON.stringify(panelData).replace(/</g, '\\u003c')}</script>
<script>
${safe(js)}
</script>
</body>
</html>
`;
const file = path.join(ROOT, 'artboards', name + 'Mock.dc.html');
fs.mkdirSync(path.dirname(file), { recursive: true });
fs.writeFileSync(file, html);
console.log(path.relative(ROOT, file));
